# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import endpoints_pb2 as proto_dot_endpoints__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/api.proto\x1a\x15proto/endpoints.proto\"\xce\x01\n\x0bRequestBody\x12$\n\x0cping_request\x18\x01 \x01(\x0b\x32\x0c.PingRequestH\x00\x12\x33\n\x14\x63reate_world_request\x18\x02 \x01(\x0b\x32\x13.CreateWorldRequestH\x00\x12-\n\x11get_world_request\x18\x03 \x01(\x0b\x32\x10.GetWorldRequestH\x00\x12-\n\x11make_step_request\x18\x04 \x01(\x0b\x32\x10.MakeStepRequestH\x00\x42\x06\n\x04\x62ody\"\xd7\x01\n\x0cResponseBody\x12&\n\rping_response\x18\x01 \x01(\x0b\x32\r.PingResponseH\x00\x12\x35\n\x15\x63reate_world_response\x18\x02 \x01(\x0b\x32\x14.CreateWorldResponseH\x00\x12/\n\x12get_world_response\x18\x03 \x01(\x0b\x32\x11.GetWorldResponseH\x00\x12/\n\x12make_step_response\x18\x04 \x01(\x0b\x32\x11.MakeStepResponseH\x00\x42\x06\n\x04\x62ody\"^\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x1a\n\x04type\x18\x03 \x01(\x0e\x32\x0c.RequestType\x12\x1a\n\x04\x62ody\x18\x04 \x01(\x0b\x32\x0c.RequestBody\"~\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1a\n\x04type\x18\x02 \x01(\x0e\x32\x0c.RequestType\x12\x1b\n\x04\x62ody\x18\x03 \x01(\x0b\x32\r.ResponseBody\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x12\n\x05\x65rror\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_errorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTBODY']._serialized_start=43
  _globals['_REQUESTBODY']._serialized_end=249
  _globals['_RESPONSEBODY']._serialized_start=252
  _globals['_RESPONSEBODY']._serialized_end=467
  _globals['_REQUEST']._serialized_start=469
  _globals['_REQUEST']._serialized_end=563
  _globals['_RESPONSE']._serialized_start=565
  _globals['_RESPONSE']._serialized_end=691
# @@protoc_insertion_point(module_scope)
