# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/endpoints.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import world_pb2 as proto_dot_world__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/endpoints.proto\x1a\x11proto/world.proto\"\r\n\x0bPingRequest\"\'\n\x12\x43reateWorldRequest\x12\x11\n\tgrid_size\x18\x01 \x01(\x05\"\x11\n\x0fGetWorldRequest\"$\n\x0fMakeStepRequest\x12\x11\n\tnum_steps\x18\x01 \x01(\x05\"\x0e\n\x0cPingResponse\"\x15\n\x13\x43reateWorldResponse\")\n\x10GetWorldResponse\x12\x15\n\x05world\x18\x01 \x01(\x0b\x32\x06.World\"\x12\n\x10MakeStepResponse*G\n\x0bRequestType\x12\x08\n\x04PING\x10\x00\x12\x10\n\x0c\x43REATE_WORLD\x10\x01\x12\r\n\tGET_WORLD\x10\x02\x12\r\n\tMAKE_STEP\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.endpoints_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTTYPE']._serialized_start=259
  _globals['_REQUESTTYPE']._serialized_end=330
  _globals['_PINGREQUEST']._serialized_start=44
  _globals['_PINGREQUEST']._serialized_end=57
  _globals['_CREATEWORLDREQUEST']._serialized_start=59
  _globals['_CREATEWORLDREQUEST']._serialized_end=98
  _globals['_GETWORLDREQUEST']._serialized_start=100
  _globals['_GETWORLDREQUEST']._serialized_end=117
  _globals['_MAKESTEPREQUEST']._serialized_start=119
  _globals['_MAKESTEPREQUEST']._serialized_end=155
  _globals['_PINGRESPONSE']._serialized_start=157
  _globals['_PINGRESPONSE']._serialized_end=171
  _globals['_CREATEWORLDRESPONSE']._serialized_start=173
  _globals['_CREATEWORLDRESPONSE']._serialized_end=194
  _globals['_GETWORLDRESPONSE']._serialized_start=196
  _globals['_GETWORLDRESPONSE']._serialized_end=237
  _globals['_MAKESTEPRESPONSE']._serialized_start=239
  _globals['_MAKESTEPRESPONSE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
