# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/world.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/world.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x1c\n\x05World\x12\x13\n\x04grid\x18\x01 \x01(\x0b\x32\x05.Grid\"\x19\n\x04Grid\x12\x11\n\x03row\x18\x01 \x03(\x0b\x32\x04.Row\"0\n\x03Row\x12)\n\x04\x63\x65ll\x18\x01 \x03(\x0b\x32\x1b.google.protobuf.Int32Valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.world_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WORLD']._serialized_start=53
  _globals['_WORLD']._serialized_end=81
  _globals['_GRID']._serialized_start=83
  _globals['_GRID']._serialized_end=108
  _globals['_ROW']._serialized_start=110
  _globals['_ROW']._serialized_end=158
# @@protoc_insertion_point(module_scope)
